### Get all campuses
GET localhost:8080/api/campuses

### Get Specific Campus
GET localhost:8080/api/campuses/1

### Deletes a specific campus
DELETE localhost:8080/api/campuses/1

### Add a new campus
POST localhost:8080/api/campuses
Content-Type: application/json

{"location": "online", "techStack": "Java"}